In [38]:
import pandas as pd

In [ ]:
day_to_sec = 86400

In [ ]:
idx = pd.date_range('2023-01-01', periods=day_to_sec, freq='S')
print(idx)

In [ ]:
data_columns = ['data01', 'data02', 'data03', 'data04']

data_example = pd.DataFrame([[i, i * 2, i * i, 0] for i in range(idx.shape[0])], index=idx, columns=data_columns)
print(data_example)

In [ ]:
data_hourly_mean = pd.DataFrame()
data_hourly_mean[data_columns] = data_example[data_columns].resample('60T').mean()
print(data_hourly_mean)

In [48]:
working_hour = pd.DataFrame()
working_hour['start'] = ['2023-01-01 09:00:00']
working_hour['end'] = ['2023-01-01 18:00:00']

working_hour['start'] = pd.to_datetime(working_hour['start'], errors='coerce')
working_hour['end'] = pd.to_datetime(working_hour['end'], errors='coerce')

working_hour['net'] = working_hour['end'] - working_hour['start']
print(working_hour)

                start                 end             net
0 2023-01-01 09:00:00 2023-01-01 18:00:00 0 days 09:00:00

In [49]:
idx = pd.date_range(start='2023-01-01 09:00:00', end='2023-01-01 18:00:00', freq='1H')
print(idx)

DatetimeIndex(['2023-01-01 09:00:00', '2023-01-01 10:00:00',
               '2023-01-01 11:00:00', '2023-01-01 12:00:00',
               '2023-01-01 13:00:00', '2023-01-01 14:00:00',
               '2023-01-01 15:00:00', '2023-01-01 16:00:00',
               '2023-01-01 17:00:00', '2023-01-01 18:00:00'],
              dtype='datetime64[ns]', freq='H')

In [50]:
data_hourly_mean['data04'].loc[idx] = 1

In [51]:
data_hourly_mean

                     data01  data02        data03  data04
2023-01-01 00:00:00    29.5    59.0  1.170167e+03     0.0
2023-01-01 01:00:00    89.5   179.0  8.310167e+03     0.0
2023-01-01 02:00:00   149.5   299.0  2.265017e+04     0.0
2023-01-01 03:00:00   209.5   419.0  4.419017e+04     0.0
2023-01-01 04:00:00   269.5   539.0  7.293017e+04     0.0
2023-01-01 05:00:00   329.5   659.0  1.088702e+05     0.0
2023-01-01 06:00:00   389.5   779.0  1.520102e+05     0.0
2023-01-01 07:00:00   449.5   899.0  2.023502e+05     0.0
2023-01-01 08:00:00   509.5  1019.0  2.598902e+05     0.0
2023-01-01 09:00:00   569.5  1139.0  3.246302e+05     1.0
2023-01-01 10:00:00   629.5  1259.0  3.965702e+05     1.0
2023-01-01 11:00:00   689.5  1379.0  4.757102e+05     1.0
2023-01-01 12:00:00   749.5  1499.0  5.620502e+05     1.0
2023-01-01 13:00:00   809.5  1619.0  6.555902e+05     1.0
2023-01-01 14:00:00   869.5  1739.0  7.563302e+05     1.0
2023-01-01 15:00:00   929.5  1859.0  8.642702e+05     1.0
2023-01-01 16:00:00   989.5  1979.0  9.794102e+05     1.0
2023-01-01 17:00:00  1049.5  2099.0  1.101750e+06     1.0
2023-01-01 18:00:00  1109.5  2219.0  1.231290e+06     1.0
2023-01-01 19:00:00  1169.5  2339.0  1.368030e+06     0.0
2023-01-01 20:00:00  1229.5  2459.0  1.511970e+06     0.0
2023-01-01 21:00:00  1289.5  2579.0  1.663110e+06     0.0
2023-01-01 22:00:00  1349.5  2699.0  1.821450e+06     0.0
2023-01-01 23:00:00  1409.5  2819.0  1.986990e+06     0.0